import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		catalog: "src/catalog.ts",
		metadata: "src/metadata.ts",
		project: "src/project.ts",
		extension: "src/extension.ts",
		cli: "src/cli.ts",
		"lucide/index": "src/lucide/index.ts",
		"lucide/catalog": "src/lucide/catalog.ts",
		"lucide/metadata": "src/lucide/metadata.ts",
		"lucide/react": "src/lucide/react.tsx",
		"tabler/index": "src/tabler/index.ts",
		"tabler/catalog": "src/tabler/catalog.ts",
		"tabler/metadata": "src/tabler/metadata.ts",
		"tabler/react": "src/tabler/react.tsx",
		"hugeicons/index": "src/hugeicons/index.ts",
		"hugeicons/catalog": "src/hugeicons/catalog.ts",
		"hugeicons/metadata": "src/hugeicons/metadata.ts",
		"hugeicons/react": "src/hugeicons/react.tsx",
		"phosphor/index": "src/phosphor/index.ts",
		"phosphor/catalog": "src/phosphor/catalog.ts",
		"phosphor/metadata": "src/phosphor/metadata.ts",
		"phosphor/react": "src/phosphor/react.tsx",
		"remix/index": "src/remix/index.ts",
		"remix/catalog": "src/remix/catalog.ts",
		"remix/metadata": "src/remix/metadata.ts",
		"remix/react": "src/remix/react.tsx",
	},
	format: ["esm", "cjs"],
	dts: true,
	clean: true,
	sourcemap: true,
	splitting: false,
	external: [
		"@json-render/core",
		"@json-render/react",
		"lucide-react",
		/^lucide-react\//,
		"@tabler/icons-react",
		/^@tabler\/icons-react\//,
		"@hugeicons/core-free-icons",
		/^@hugeicons\/core-free-icons\//,
		"@hugeicons/react",
		/^@hugeicons\/react\//,
		"@phosphor-icons/react",
		/^@phosphor-icons\/react\//,
		"@remixicon/react",
		/^@remixicon\/react\//,
		"react",
		"react-dom",
		"zod",
	],
});
