/* Generated by @json-render-extended/playground. Do not edit manually. */

import type { JsonRenderSpecEntries } from "@json-render-extended/playground/runtime";
import { PackageSurface as MaterializedSpec0 } from "../components/generated/package-surface";

export const jsonRenderSpecs = {
	"docs/package-surface": { mode: "materialized", Component: MaterializedSpec0 },
	"docs/runtime-notice": {
		mode: "runtime",
		spec: {
			root: "notice",
			state: {
				props: {
					title: "Runtime JSON Render spec",
					message:
						"This spec stays as JSON in production because it has no materialization receipt.",
				},
			},
			elements: {
				notice: {
					type: "Alert",
					props: {
						title: {
							$state: "/props/title",
						},
						message: {
							$state: "/props/message",
						},
						type: "info",
					},
				},
			},
		},
	},
} satisfies JsonRenderSpecEntries;
