/* Generated by @json-render-extended/core. Do not edit manually. */

import { componentDefinitions as extension3CatalogComponents } from "../json-render/materialized/catalog";
import { components as extension3RuntimeComponents } from "../json-render/materialized/registry";
import { componentDefinitions as extension2CatalogComponents } from "@/lib/json-render-extended/code-block-composition-1.catalog";
import { components as extension2RuntimeComponents } from "@/lib/json-render-extended/code-block-composition-1.registry";
import { tablerComponentDefinitions as extension0CatalogComponents } from "@json-render-extended/icons/tabler/catalog";
import { tablerComponents as extension0RuntimeComponents } from "@json-render-extended/icons/tabler/react";
import { baseUiComponents as extension1RuntimeComponents } from "@json-render-extended/shadcn/base-ui";
import { shadcnComponentDefinitions as extension1CatalogComponents } from "@json-render-extended/shadcn/catalog";

interface ExtensionEntry {
	id: string;
	catalogComponents: Record<string, unknown>;
	catalogActions: Record<string, unknown>;
	runtimeComponents: Record<string, unknown>;
	runtimeActions: Record<string, unknown>;
	componentOverrides: readonly string[];
	actionOverrides: readonly string[];
}

type SurfaceName =
	| "catalogComponents"
	| "catalogActions"
	| "runtimeComponents"
	| "runtimeActions";

type SurfaceOverrides = "componentOverrides" | "actionOverrides";

type UnionToIntersection<Union> = (
	Union extends unknown ? (value: Union) => void : never
) extends (value: infer Intersection) => void
	? Intersection
	: never;

function indexExtensionSurface<
	const Entries extends readonly ExtensionEntry[],
	const Surface extends SurfaceName,
>(entries: Entries, surface: Surface) {
	return Object.fromEntries(entries.map((entry) => [entry.id, entry[surface]])) as {
		[Entry in Entries[number] as Entry["id"]]: Entry[Surface];
	};
}

function mergeExtensionSurface<
	const Entries extends readonly ExtensionEntry[],
	const Surface extends SurfaceName,
>(
	label: string,
	entries: Entries,
	surface: Surface,
	overrides: SurfaceOverrides,
): UnionToIntersection<Entries[number][Surface]> {
	const merged: Record<string, unknown> = {};
	const owners = new Map<string, string>();
	for (const entry of entries) {
		for (const [key, value] of Object.entries(entry[surface])) {
			const owner = owners.get(key);
			if (owner && !entry[overrides].includes(key)) {
				throw new Error(
					`JSON Render Extended collision in ${label}: ${key} is provided by ${owner} and ${entry.id}. Declare an explicit override to replace it.`,
				);
			}
			merged[key] = value;
			owners.set(key, entry.id);
		}
	}
	return merged as UnionToIntersection<Entries[number][Surface]>;
}

export const extensionEntries = [
	{
		id: "@json-render-extended/icons/tabler",
		catalogComponents: extension0CatalogComponents,
		catalogActions: {},
		runtimeComponents: extension0RuntimeComponents,
		runtimeActions: {},
		componentOverrides: [],
		actionOverrides: [],
	},
	{
		id: "@json-render-extended/shadcn",
		catalogComponents: extension1CatalogComponents,
		catalogActions: {},
		runtimeComponents: extension1RuntimeComponents,
		runtimeActions: {},
		componentOverrides: [],
		actionOverrides: [],
	},
	{
		id: "registry:@jr-ext:@jr-ext/code-block-composition-1",
		catalogComponents: extension2CatalogComponents,
		catalogActions: {},
		runtimeComponents: extension2RuntimeComponents,
		runtimeActions: {},
		componentOverrides: [],
		actionOverrides: [],
	},
	{
		id: "local:materialized",
		catalogComponents: extension3CatalogComponents,
		catalogActions: {},
		runtimeComponents: extension3RuntimeComponents,
		runtimeActions: {},
		componentOverrides: ["Alert","Badge","Card"],
		actionOverrides: [],
	},
] as const satisfies readonly ExtensionEntry[];

export const project = {
	"runtime": "react",
	"configPath": "json-render-extended.config.ts",
	"extensions": [
		{
			"id": "@json-render-extended/icons/tabler",
			"version": null,
			"description": "JSON Render Icon catalog and renderer for tabler.",
			"styles": [],
			"capabilities": {
				"description": "A validated semantic icon vocabulary with intent-based retrieval.",
				"tags": [
					"icons",
					"semantic-retrieval",
					"tabler"
				],
				"skills": [
					"json-render-icons"
				]
			},
			"authoring": null,
			"provenance": {
				"packageName": "@tabler/icons-react",
				"source": "built-in"
			}
		},
		{
			"id": "@json-render-extended/shadcn",
			"version": null,
			"description": "Multi-base shadcn registry using base-ui/nova.",
			"styles": [
				"@json-render-extended/shadcn/tailwind.css"
			],
			"capabilities": {
				"description": "shadcn component definitions and interchangeable primitive registries.",
				"tags": [
					"components",
					"shadcn",
					"base-ui",
					"nova"
				],
				"skills": [
					"json-render-shadcn"
				]
			},
			"authoring": {
				"playground": {
					"module": "@json-render-extended/shadcn/authoring",
					"export": "shadcnAuthoringProvider"
				}
			},
			"provenance": {
				"packageName": "@json-render-extended/shadcn",
				"source": "@json-render-extended/shadcn/base-ui#baseUiComponents",
				"version": "0.0.0"
			}
		},
		{
			"id": "registry:@jr-ext:@jr-ext/code-block-composition-1",
			"version": null,
			"description": "JSON Render extension discovered from @jr-ext.",
			"styles": [],
			"capabilities": {
				"tags": [
					"registry-extension",
					"@jr-ext"
				]
			},
			"authoring": null,
			"provenance": {
				"packageName": "@jr-ext/code-block-composition-1",
				"source": "installed:@jr-ext/code-block-composition-1"
			}
		},
		{
			"id": "local:materialized",
			"version": null,
			"description": "Project-local components materialized from repository-backed JSON Render specs.",
			"styles": [],
			"capabilities": {
				"description": "Materialized composite specs and application-owned primitive overrides.",
				"tags": [
					"local",
					"materialized",
					"components"
				]
			},
			"authoring": null,
			"provenance": {
				"source": "project-local:json-render/materializations"
			}
		}
	],
	"diagnostics": []
} as const;

export const styles = [
	"@json-render-extended/shadcn/tailwind.css"
] as const;

export const componentDefinitionsByExtension = indexExtensionSurface(
	extensionEntries,
	"catalogComponents",
);

export const actionDefinitionsByExtension = indexExtensionSurface(
	extensionEntries,
	"catalogActions",
);

export const componentsByExtension = indexExtensionSurface(
	extensionEntries,
	"runtimeComponents",
);

export const actionsByExtension = indexExtensionSurface(extensionEntries, "runtimeActions");

export const componentDefinitions = mergeExtensionSurface(
	"catalog components",
	extensionEntries,
	"catalogComponents",
	"componentOverrides",
);

export const actionDefinitions = mergeExtensionSurface(
	"catalog actions",
	extensionEntries,
	"catalogActions",
	"actionOverrides",
);

export const components = mergeExtensionSurface(
	"runtime components",
	extensionEntries,
	"runtimeComponents",
	"componentOverrides",
);

export const actions = mergeExtensionSurface(
	"runtime actions",
	extensionEntries,
	"runtimeActions",
	"actionOverrides",
);
