import type { ShadcnBase } from "./bases";

export const implementedJsonRenderComponentNames = [
	"Accordion",
	"Alert",
	"AlertDialog",
	"AspectRatio",
	"Attachment",
	"Avatar",
	"Badge",
	"Breadcrumb",
	"Bubble",
	"Button",
	"ButtonGroup",
	"Calendar",
	"Card",
	"Carousel",
	"Chart",
	"Checkbox",
	"Collapsible",
	"Combobox",
	"Command",
	"ContextMenu",
	"Dialog",
	"Direction",
	"Drawer",
	"DropdownMenu",
	"Empty",
	"Field",
	"Form",
	"Grid",
	"Heading",
	"HoverCard",
	"Image",
	"Input",
	"InputGroup",
	"InputOtp",
	"Item",
	"Kbd",
	"Label",
	"Link",
	"Marker",
	"Menubar",
	"Message",
	"MessageScroller",
	"NativeSelect",
	"NavigationMenu",
	"Pagination",
	"Popover",
	"Progress",
	"Radio",
	"Resizable",
	"ScrollArea",
	"Select",
	"Separator",
	"Sheet",
	"Sidebar",
	"Skeleton",
	"Slider",
	"Sonner",
	"Spinner",
	"Stack",
	"Switch",
	"Table",
	"Tabs",
	"Text",
	"Textarea",
	"Toast",
	"Toggle",
	"ToggleGroup",
	"Tooltip",
] as const;

export const multiBaseComponentNames = implementedJsonRenderComponentNames;

export const fallbackJsonRenderComponentNamesByBase = {
	"base-ui": ["Toast"],
	"react-aria": ["HoverCard", "Menubar", "NavigationMenu", "Toast"],
	radix: ["Toast"],
} as const satisfies Record<ShadcnBase, readonly ImplementedJsonRenderComponentName[]>;

export type ImplementedJsonRenderComponentName =
	(typeof implementedJsonRenderComponentNames)[number];
export type MultiBaseComponentName = ImplementedJsonRenderComponentName;
