import { relative, resolve, sep } from "node:path";

import {
	type AuthoringComponentProp,
	type AuthoringRuntimeComposition,
	jsonRenderExtensionProtocol,
} from "@json-render-extended/core";

export interface MaterializedComponentRegistration {
	specId: string;
	key: string;
	module: string;
	export: string;
	props: readonly AuthoringComponentProp[];
}

export interface LocalRegistryMaterialization {
	component: MaterializedComponentRegistration;
	runtimeCompositions: readonly AuthoringRuntimeComposition[];
}

export interface RenderedLocalRegistry {
	catalogPath: string;
	catalogSource: string;
	manifestPath: string;
	manifestSource: string;
	registryPath: string;
	registrySource: string;
}

export function renderLocalMaterializedRegistry(
	projectRoot: string,
	materializations: readonly LocalRegistryMaterialization[],
): RenderedLocalRegistry {
	const catalogPath = resolve(projectRoot, "json-render/materialized/catalog.ts");
	const registryPath = resolve(projectRoot, "json-render/materialized/registry.tsx");
	const manifestPath = resolve(projectRoot, "json-render/extensions/materialized.json");
	const records = [...materializations].sort((left, right) =>
		left.component.specId.localeCompare(right.component.specId),
	);
	assertUnique(
		records.map((record) => record.component.key),
		"materialized component key",
	);

	const compositions = groupRuntimeCompositions(
		records.flatMap((record) => record.runtimeCompositions),
	);
	const primitiveKeys = [
		...new Set(compositions.flatMap((composition) => composition.keys)),
	].sort();
	assertUniqueAcrossCompositions(compositions);
	const componentKeys = records.map((record) => record.component.key);
	const runtimeKeys = [...new Set([...primitiveKeys, ...componentKeys])].sort();

	return {
		catalogPath,
		catalogSource: renderCatalog(records),
		manifestPath,
		manifestSource: `${JSON.stringify(
			{
				protocol: jsonRenderExtensionProtocol,
				id: "local:materialized",
				description:
					"Project-local components materialized from repository-backed JSON Render specs.",
				catalog: {
					components: {
						module: "./json-render/materialized/catalog",
						export: "componentDefinitions",
						keys: componentKeys,
					},
				},
				runtimes: {
					react: {
						components: {
							module: "./json-render/materialized/registry",
							export: "components",
							keys: runtimeKeys,
						},
					},
				},
				overrides: { components: primitiveKeys },
				capabilities: {
					description: "Materialized composite specs and application-owned primitive overrides.",
					tags: ["local", "materialized", "components"],
				},
				provenance: { source: "project-local:json-render/materializations" },
			},
			null,
			"\t",
		)}\n`,
		registryPath,
		registrySource: renderRegistry(projectRoot, registryPath, records, compositions),
	};
}

function renderCatalog(records: readonly LocalRegistryMaterialization[]) {
	return `/* Generated by @json-render-extended/playground. Do not edit manually. */

import { z } from "zod";

export const componentDefinitions = {
${records
	.map(
		(record) => `\t${JSON.stringify(record.component.key)}: {
\t\tprops: z.object({
${record.component.props
	.map((prop) => `\t\t\t${JSON.stringify(prop.name)}: ${renderZodProp(prop)},`)
	.join("\n")}
\t\t}),
\t\tdescription: ${JSON.stringify(`Project-local component materialized from ${record.component.specId}.`)},
\t\texample: {},
\t},`,
	)
	.join("\n")}
};
`;
}

function renderRegistry(
	projectRoot: string,
	registryPath: string,
	records: readonly LocalRegistryMaterialization[],
	compositions: readonly AuthoringRuntimeComposition[],
) {
	const imports: string[] = [];
	const moduleAliases = new Map<string, string>();
	for (const composition of compositions) {
		for (const moduleName of composition.modules) {
			if (moduleAliases.has(moduleName)) continue;
			const alias = `localPrimitives${moduleAliases.size}`;
			moduleAliases.set(moduleName, alias);
			imports.push(`import * as ${alias} from ${JSON.stringify(moduleName)};`);
		}
	}
	for (const [index, composition] of compositions.entries()) {
		imports.push(
			composition.factory.export === "default"
				? `import createRuntimeComponents${index} from ${JSON.stringify(composition.factory.module)};`
				: `import { ${composition.factory.export} as createRuntimeComponents${index} } from ${JSON.stringify(composition.factory.module)};`,
		);
	}
	for (const record of records) {
		imports.push(
			`import { ${record.component.export} } from ${JSON.stringify(outputModuleSpecifier(projectRoot, registryPath, record.component.module))};`,
		);
	}

	const runtimeDeclarations = compositions.map(
		(composition, index) =>
			`const runtimeComponents${index} = createRuntimeComponents${index}(${composition.modules
				.map((moduleName) => moduleAliases.get(moduleName))
				.join(", ")});`,
	);
	const rendererDeclarations = records.map(
		(
			record,
		) => `function ${record.component.key}Renderer(${record.component.props.length > 0 ? "{ props }: BaseComponentProps<Record<string, unknown>>" : ""}) {
\treturn <${record.component.export}${record.component.props.length > 0 ? " {...props}" : ""} />;
}`,
	);
	const primitiveEntries = compositions.flatMap((composition, index) =>
		composition.keys.map(
			(key) => `\t${JSON.stringify(key)}: ${memberAccess(`runtimeComponents${index}`, key)},`,
		),
	);
	const componentEntries = records.map(
		(record) => `\t${JSON.stringify(record.component.key)}: ${record.component.key}Renderer,`,
	);

	const needsRenderProps = records.some((record) => record.component.props.length > 0);
	return `/* Generated by @json-render-extended/playground. Do not edit manually. */
"use client";

${needsRenderProps ? 'import type { BaseComponentProps } from "@json-render/react";\n' : ""}${imports.sort().join("\n")}

${runtimeDeclarations.join("\n")}

${rendererDeclarations.join("\n\n")}

export const components = {
${[...primitiveEntries, ...componentEntries].join("\n")}
};
`;
}

function renderZodProp(prop: AuthoringComponentProp) {
	const schema = {
		array: "z.array(z.unknown())",
		boolean: "z.boolean()",
		number: "z.number()",
		object: "z.record(z.string(), z.unknown())",
		string: "z.string()",
		unknown: "z.unknown()",
	}[prop.type];
	return `${schema}.optional()`;
}

function groupRuntimeCompositions(compositions: readonly AuthoringRuntimeComposition[]) {
	const groups = new Map<string, AuthoringRuntimeComposition>();
	for (const composition of compositions) {
		const id = `${composition.factory.module}#${composition.factory.export}`;
		const current = groups.get(id);
		groups.set(id, {
			factory: composition.factory,
			modules: [...new Set([...(current?.modules ?? []), ...composition.modules])].sort(),
			keys: [...new Set([...(current?.keys ?? []), ...composition.keys])].sort(),
		});
	}
	return [...groups.values()].sort((left, right) =>
		`${left.factory.module}#${left.factory.export}`.localeCompare(
			`${right.factory.module}#${right.factory.export}`,
		),
	);
}

function assertUniqueAcrossCompositions(compositions: readonly AuthoringRuntimeComposition[]) {
	const owners = new Map<string, string>();
	for (const composition of compositions) {
		const owner = `${composition.factory.module}#${composition.factory.export}`;
		for (const key of composition.keys) {
			const previous = owners.get(key);
			if (previous && previous !== owner) {
				throw new Error(
					`Local runtime component ${key} is produced by both ${previous} and ${owner}. Select one authoring provider for that component.`,
				);
			}
			owners.set(key, owner);
		}
	}
}

function assertUnique(values: readonly string[], label: string) {
	const seen = new Set<string>();
	for (const value of values) {
		if (seen.has(value))
			throw new Error(`Duplicate ${label} ${value}. Choose a distinct output name.`);
		seen.add(value);
	}
}

function memberAccess(object: string, key: string) {
	return /^[$A-Z_a-z][$\w]*$/.test(key) ? `${object}.${key}` : `${object}[${JSON.stringify(key)}]`;
}

function outputModuleSpecifier(projectRoot: string, registryPath: string, modulePath: string) {
	const absolute = resolve(projectRoot, modulePath);
	const value = relative(resolve(registryPath, ".."), absolute).split(sep).join("/");
	return value.startsWith(".") ? value : `./${value}`;
}
