import { randomUUID } from "node:crypto";
import { access, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { formatProjectSource } from "./format";
import {
	type MaterializationReceipt,
	materializationProtocol,
	materializeSpec,
} from "./materialize";
import { digestSpec } from "./session";
import {
	ProjectSpecStore,
	type ResolveTargetProjectOptions,
	resolveTargetProject,
} from "./spec-store";

export interface BuildSpecModuleOptions extends ResolveTargetProjectOptions {
	output?: string;
	refreshMaterializations?: boolean;
}

export async function buildSpecModule(options: BuildSpecModuleOptions = {}) {
	const target = await resolveTargetProject(options);
	const store = new ProjectSpecStore(target);
	const specIds = await store.list();
	if (options.refreshMaterializations) {
		for (const specId of specIds) {
			const receipt = await readMaterializationReceipt(target.projectRoot, specId);
			if (!receipt) continue;
			for (const output of receipt.outputs) {
				await materializeSpec({
					cwd: target.projectRoot,
					specDirectory: target.specDirectory,
					specId,
					providerId: receipt.providerId,
					output: output.path,
				});
			}
		}
	}

	const outputPath = resolve(target.projectRoot, options.output ?? "json-render/specs.ts");
	assertInside(target.projectRoot, outputPath);
	const imports = [
		'import type { JsonRenderSpecEntries } from "@json-render-extended/playground/runtime";',
	];
	const entries: string[] = [];
	const diagnostics: string[] = [];
	for (const [index, specId] of specIds.entries()) {
		const spec = await store.read(specId);
		const receipt = await readMaterializationReceipt(target.projectRoot, specId);
		if (
			receipt &&
			receipt.sourceDigest === digestSpec(spec.value) &&
			receipt.outputs.length > 0 &&
			(await materializedComponentExists(target.projectRoot, receipt))
		) {
			const componentAlias = `MaterializedSpec${index}`;
			imports.push(
				`import { ${receipt.component.export} as ${componentAlias} } from ${JSON.stringify(moduleSpecifier(target.projectRoot, outputPath, receipt.component.module))};`,
			);
			entries.push(
				`\t${JSON.stringify(specId)}: { mode: "materialized", Component: ${componentAlias} },`,
			);
			continue;
		}
		if (receipt) diagnostics.push(`${specId} has a stale materialization and remains runtime.`);
		entries.push(
			`\t${JSON.stringify(specId)}: { mode: "runtime", spec: ${JSON.stringify(spec.value, null, "\t").replaceAll("\n", "\n\t")} },`,
		);
	}

	const source = `/* Generated by @json-render-extended/playground. Do not edit manually. */

${imports.join("\n")}

export const jsonRenderSpecs = {
${entries.join("\n")}
} satisfies JsonRenderSpecEntries;
`;
	await atomicWrite(outputPath, source);
	await formatProjectSource(target.packageJsonPath, outputPath);
	return { target, outputPath, specIds, diagnostics };
}

async function readMaterializationReceipt(projectRoot: string, specId: string) {
	try {
		const value = JSON.parse(
			await readFile(
				resolve(projectRoot, "json-render/materializations", `${specId}.json`),
				"utf8",
			),
		) as MaterializationReceipt;
		return value.protocol === materializationProtocol && value.component ? value : null;
	} catch {
		return null;
	}
}

async function materializedComponentExists(projectRoot: string, receipt: MaterializationReceipt) {
	try {
		await access(resolve(projectRoot, receipt.outputs[0]?.path ?? ""));
		return true;
	} catch {
		return false;
	}
}

function moduleSpecifier(projectRoot: string, outputPath: string, modulePath: string) {
	const value = relative(dirname(outputPath), resolve(projectRoot, modulePath))
		.split(sep)
		.join("/");
	return value.startsWith(".") ? value : `./${value}`;
}

async function atomicWrite(path: string, source: string) {
	await mkdir(dirname(path), { recursive: true });
	const temporaryPath = `${path}.${process.pid}.${randomUUID()}.tmp`;
	await writeFile(temporaryPath, source, "utf8");
	await rename(temporaryPath, path);
}

function assertInside(parent: string, child: string) {
	const value = relative(parent, child);
	if (value.startsWith("..") || value === "..") {
		throw new Error(`The generated spec module must stay inside ${parent}.`);
	}
}
