import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import {
	type ResolvedExtensionProject,
	type ResolveExtensionProjectOptions,
	resolveExtensionProject,
} from "./project";
import type {
	ExtensionDiagnostic,
	ExtensionSurfaceReference,
	JsonRenderExtension,
} from "./protocol";

export interface RenderExtensionProjectModuleOptions {
	outputPath?: string;
}

export interface GenerateExtensionProjectModuleOptions extends ResolveExtensionProjectOptions {
	output?: string;
}

export interface GeneratedExtensionProjectModule {
	outputPath: string;
	project: ResolvedExtensionProject;
	code: string;
}

interface RenderedExtensionEntry {
	id: string;
	catalogComponents: string;
	catalogActions: string;
	runtimeComponents: string;
	runtimeActions: string;
	componentOverrides: readonly string[];
	actionOverrides: readonly string[];
}

interface RenderedImport {
	module: string;
	statement: string;
}

export async function generateExtensionProjectModule(
	options: GenerateExtensionProjectModuleOptions = {},
): Promise<GeneratedExtensionProjectModule> {
	const project = await resolveExtensionProject(options);
	const outputPath = resolve(project.cwd, options.output ?? "json-render-extended.generated.ts");
	const diagnostics = validateDeclaredExtensionCollisions(project);
	project.diagnostics.push(...diagnostics);
	if (
		(options.strict ?? project.strict) &&
		diagnostics.some((diagnostic) => diagnostic.severity === "error")
	) {
		throw new Error(diagnostics.find((diagnostic) => diagnostic.severity === "error")?.message);
	}
	const code = renderExtensionProjectModule(project, { outputPath });
	await mkdir(dirname(outputPath), { recursive: true });
	await writeFile(outputPath, code, "utf8");
	return { outputPath, project, code };
}

export function renderExtensionProjectModule(
	project: ResolvedExtensionProject,
	options: RenderExtensionProjectModuleOptions = {},
): string {
	const outputPath = resolve(
		project.cwd,
		options.outputPath ?? "json-render-extended.generated.ts",
	);
	const imports: RenderedImport[] = [];
	const entries: RenderedExtensionEntry[] = [];

	for (const [index, extension] of project.extensions.entries()) {
		const runtime = extension.runtimes[project.runtime] ?? {};
		entries.push({
			id: extension.id,
			catalogComponents: renderSurfaceImport({
				reference: extension.catalog.components,
				alias: `extension${index}CatalogComponents`,
				imports,
				project,
				outputPath,
			}),
			catalogActions: renderSurfaceImport({
				reference: extension.catalog.actions,
				alias: `extension${index}CatalogActions`,
				imports,
				project,
				outputPath,
			}),
			runtimeComponents: renderSurfaceImport({
				reference: runtime.components,
				alias: `extension${index}RuntimeComponents`,
				imports,
				project,
				outputPath,
			}),
			runtimeActions: renderSurfaceImport({
				reference: runtime.actions,
				alias: `extension${index}RuntimeActions`,
				imports,
				project,
				outputPath,
			}),
			componentOverrides: extension.overrides?.components ?? [],
			actionOverrides: extension.overrides?.actions ?? [],
		});
	}

	const metadata = {
		runtime: project.runtime,
		configPath: project.configPath ? relative(project.cwd, project.configPath) : null,
		extensions: project.extensions.map(extensionMetadata),
		diagnostics: project.diagnostics,
	};
	const styles = [...new Set(project.extensions.flatMap((extension) => extension.styles ?? []))];

	return `/* Generated by @json-render-extended/core. Do not edit manually. */

${imports
	.sort((left, right) => left.module.localeCompare(right.module))
	.map((entry) => entry.statement)
	.join("\n")}

interface ExtensionEntry {
\tid: string;
\tcatalogComponents: Record<string, unknown>;
\tcatalogActions: Record<string, unknown>;
\truntimeComponents: Record<string, unknown>;
\truntimeActions: Record<string, unknown>;
\tcomponentOverrides: readonly string[];
\tactionOverrides: readonly string[];
}

type SurfaceName =
\t| "catalogComponents"
\t| "catalogActions"
\t| "runtimeComponents"
\t| "runtimeActions";

type SurfaceOverrides = "componentOverrides" | "actionOverrides";

type UnionToIntersection<Union> = (
\tUnion extends unknown ? (value: Union) => void : never
) extends (value: infer Intersection) => void
\t? Intersection
\t: never;

function indexExtensionSurface<
\tconst Entries extends readonly ExtensionEntry[],
\tconst Surface extends SurfaceName,
>(entries: Entries, surface: Surface) {
\treturn Object.fromEntries(entries.map((entry) => [entry.id, entry[surface]])) as {
\t\t[Entry in Entries[number] as Entry["id"]]: Entry[Surface];
\t};
}

function mergeExtensionSurface<
\tconst Entries extends readonly ExtensionEntry[],
\tconst Surface extends SurfaceName,
>(
\tlabel: string,
\tentries: Entries,
\tsurface: Surface,
\toverrides: SurfaceOverrides,
): UnionToIntersection<Entries[number][Surface]> {
\tconst merged: Record<string, unknown> = {};
\tconst owners = new Map<string, string>();
\tfor (const entry of entries) {
\t\tfor (const [key, value] of Object.entries(entry[surface])) {
\t\t\tconst owner = owners.get(key);
\t\t\tif (owner && !entry[overrides].includes(key)) {
\t\t\t\tthrow new Error(
\t\t\t\t\t\`JSON Render Extended collision in \${label}: \${key} is provided by \${owner} and \${entry.id}. Declare an explicit override to replace it.\`,
\t\t\t\t);
\t\t\t}
\t\t\tmerged[key] = value;
\t\t\towners.set(key, entry.id);
\t\t}
\t}
\treturn merged as UnionToIntersection<Entries[number][Surface]>;
}

export const extensionEntries = [
${entries.map(renderEntry).join("\n")}
] as const satisfies readonly ExtensionEntry[];

export const project = ${JSON.stringify(metadata, null, "\t")} as const;

export const styles = ${JSON.stringify(styles, null, "\t")} as const;

export const componentDefinitionsByExtension = indexExtensionSurface(
\textensionEntries,
\t"catalogComponents",
);

export const actionDefinitionsByExtension = indexExtensionSurface(
\textensionEntries,
\t"catalogActions",
);

export const componentsByExtension = indexExtensionSurface(
\textensionEntries,
\t"runtimeComponents",
);

export const actionsByExtension = indexExtensionSurface(extensionEntries, "runtimeActions");

export const componentDefinitions = mergeExtensionSurface(
\t"catalog components",
\textensionEntries,
\t"catalogComponents",
\t"componentOverrides",
);

export const actionDefinitions = mergeExtensionSurface(
\t"catalog actions",
\textensionEntries,
\t"catalogActions",
\t"actionOverrides",
);

export const components = mergeExtensionSurface(
\t"runtime components",
\textensionEntries,
\t"runtimeComponents",
\t"componentOverrides",
);

export const actions = mergeExtensionSurface(
\t"runtime actions",
\textensionEntries,
\t"runtimeActions",
\t"actionOverrides",
);
`;
}

export function validateDeclaredExtensionCollisions(
	project: ResolvedExtensionProject,
): ExtensionDiagnostic[] {
	const diagnostics: ExtensionDiagnostic[] = [];
	validateSurface("catalog components", project.extensions, "components", diagnostics);
	validateSurface("catalog actions", project.extensions, "actions", diagnostics);
	return diagnostics;
}

function validateSurface(
	label: string,
	extensions: readonly JsonRenderExtension[],
	surface: "actions" | "components",
	diagnostics: ExtensionDiagnostic[],
) {
	const owners = new Map<string, string>();
	for (const extension of extensions) {
		const reference = extension.catalog[surface];
		for (const key of reference?.keys ?? []) {
			const owner = owners.get(key);
			if (owner && !extension.overrides?.[surface]?.includes(key)) {
				diagnostics.push({
					code: "extension-surface-collision",
					message: `${label} key ${key} is declared by ${owner} and ${extension.id}.`,
					severity: "error",
					extensionId: extension.id,
				});
			}
			owners.set(key, extension.id);
		}
	}
}

function renderSurfaceImport(options: {
	reference: ExtensionSurfaceReference | undefined;
	alias: string;
	imports: RenderedImport[];
	project: ResolvedExtensionProject;
	outputPath: string;
}): string {
	if (!options.reference) return "{}";
	const moduleName = outputModuleSpecifier(
		options.reference.module,
		options.project.cwd,
		options.outputPath,
	);
	options.imports.push({
		module: moduleName,
		statement:
			options.reference.export === "default"
				? `import ${options.alias} from ${JSON.stringify(moduleName)};`
				: `import { ${options.reference.export} as ${options.alias} } from ${JSON.stringify(moduleName)};`,
	});
	return options.alias;
}

function outputModuleSpecifier(moduleName: string, cwd: string, outputPath: string): string {
	if (!moduleName.startsWith(".") && !moduleName.startsWith("/")) return moduleName;
	const absolute = moduleName.startsWith("/") ? moduleName : resolve(cwd, moduleName);
	const modulePath = relative(dirname(outputPath), absolute).split(sep).join("/");
	return modulePath.startsWith(".") ? modulePath : `./${modulePath}`;
}

function renderEntry(entry: RenderedExtensionEntry): string {
	return `\t{
\t\tid: ${JSON.stringify(entry.id)},
\t\tcatalogComponents: ${entry.catalogComponents},
\t\tcatalogActions: ${entry.catalogActions},
\t\truntimeComponents: ${entry.runtimeComponents},
\t\truntimeActions: ${entry.runtimeActions},
\t\tcomponentOverrides: ${JSON.stringify(entry.componentOverrides)},
\t\tactionOverrides: ${JSON.stringify(entry.actionOverrides)},
\t},`;
}

function extensionMetadata(extension: JsonRenderExtension) {
	return {
		id: extension.id,
		version: extension.version ?? null,
		description: extension.description ?? extension.capabilities?.description ?? null,
		styles: extension.styles ?? [],
		capabilities: extension.capabilities ?? null,
		authoring: extension.authoring ?? null,
		provenance: extension.provenance ?? null,
	};
}
