export {
	type GeneratedExtensionProjectModule,
	type GenerateExtensionProjectModuleOptions,
	generateExtensionProjectModule,
	type RenderExtensionProjectModuleOptions,
	renderExtensionProjectModule,
	validateDeclaredExtensionCollisions,
} from "./generate";
export {
	type DiscoveredExtensionPackage,
	defaultExtensionConfigNames,
	defaultLocalExtensionDirectory,
	detectExtensionPackages,
	loadExtensionConfig,
	type ResolvedExtensionProject,
	type ResolvedExtensionSource,
	type ResolvedProjectAuthoringProvider,
	type ResolveExtensionProjectOptions,
	resolveExtensionProject,
	resolveProjectAuthoringProviders,
} from "./project";
export {
	type AuthoringCodegenContext,
	type AuthoringCodegenResult,
	type AuthoringComponentProp,
	type AuthoringPreset,
	type AuthoringProviderContext,
	type AuthoringRuntimeComposition,
	defineAuthoringProvider,
	defineConfig,
	defineExtension,
	defineExtensionAdapter,
	type ExtensionAdapterContext,
	type ExtensionAdapterResult,
	type ExtensionAuthoringReferences,
	type ExtensionCapabilities,
	type ExtensionCatalogReferences,
	type ExtensionConfigEntry,
	type ExtensionDiagnostic,
	type ExtensionModuleReference,
	type ExtensionOverrides,
	type ExtensionPackageRegistration,
	type ExtensionProvenance,
	type ExtensionRuntimeReferences,
	type ExtensionSurfaceReference,
	isJsonRenderExtension,
	isProjectAuthoringProvider,
	isProjectExtensionAdapter,
	type JsonRenderExtension,
	type JsonRenderExtensionConfig,
	type JsonRenderExtensionInput,
	jsonRenderAuthoringProviderProtocol,
	jsonRenderExtensionPackageKey,
	jsonRenderExtensionProtocol,
	type ProjectAuthoringProvider,
	type ProjectAuthoringProviderInput,
	type ProjectExtensionAdapter,
	type ProjectExtensionAdapterInput,
	parseExtensionPackageRegistration,
	parseModuleReference,
	type ResolvedAuthoringProvider,
} from "./protocol";
