import type { ElementType } from "react";

export type AdditionalShadcnPrimitiveName =
	| "AlertDialog"
	| "AlertDialogAction"
	| "AlertDialogCancel"
	| "AlertDialogContent"
	| "AlertDialogDescription"
	| "AlertDialogFooter"
	| "AlertDialogHeader"
	| "AlertDialogTitle"
	| "AlertDialogTrigger"
	| "AspectRatio"
	| "Attachment"
	| "AttachmentContent"
	| "AttachmentDescription"
	| "AttachmentMedia"
	| "AttachmentTitle"
	| "Breadcrumb"
	| "BreadcrumbItem"
	| "BreadcrumbLink"
	| "BreadcrumbList"
	| "BreadcrumbPage"
	| "BreadcrumbSeparator"
	| "Bubble"
	| "BubbleContent"
	| "BubbleGroup"
	| "BubbleReactions"
	| "Calendar"
	| "ChartContainer"
	| "Combobox"
	| "ComboboxContent"
	| "ComboboxEmpty"
	| "ComboboxInput"
	| "ComboboxItem"
	| "ComboboxList"
	| "Command"
	| "CommandEmpty"
	| "CommandGroup"
	| "CommandInput"
	| "CommandItem"
	| "CommandList"
	| "CommandShortcut"
	| "ContextMenu"
	| "ContextMenuContent"
	| "ContextMenuItem"
	| "ContextMenuTrigger"
	| "DirectionProvider"
	| "Empty"
	| "EmptyContent"
	| "EmptyDescription"
	| "EmptyHeader"
	| "EmptyMedia"
	| "EmptyTitle"
	| "Field"
	| "FieldContent"
	| "FieldDescription"
	| "FieldError"
	| "FieldLabel"
	| "HoverCard"
	| "HoverCardContent"
	| "HoverCardTrigger"
	| "InputGroup"
	| "InputGroupAddon"
	| "InputGroupInput"
	| "InputGroupText"
	| "InputOTP"
	| "InputOTPGroup"
	| "InputOTPSeparator"
	| "InputOTPSlot"
	| "Item"
	| "ItemActions"
	| "ItemContent"
	| "ItemDescription"
	| "ItemMedia"
	| "ItemTitle"
	| "Kbd"
	| "KbdGroup"
	| "Marker"
	| "MarkerContent"
	| "Menubar"
	| "MenubarContent"
	| "MenubarItem"
	| "MenubarMenu"
	| "MenubarTrigger"
	| "Message"
	| "MessageAvatar"
	| "MessageContent"
	| "MessageFooter"
	| "MessageGroup"
	| "MessageHeader"
	| "MessageScroller"
	| "MessageScrollerContent"
	| "MessageScrollerProvider"
	| "MessageScrollerViewport"
	| "NativeSelect"
	| "NativeSelectOption"
	| "NavigationMenu"
	| "NavigationMenuItem"
	| "NavigationMenuLink"
	| "NavigationMenuList"
	| "ResizableHandle"
	| "ResizablePanel"
	| "ResizablePanelGroup"
	| "ScrollArea"
	| "ScrollBar"
	| "Sheet"
	| "SheetContent"
	| "SheetDescription"
	| "SheetHeader"
	| "SheetTitle"
	| "SheetTrigger"
	| "Sidebar"
	| "SidebarContent"
	| "SidebarGroup"
	| "SidebarGroupContent"
	| "SidebarGroupLabel"
	| "SidebarHeader"
	| "SidebarMenu"
	| "SidebarMenuButton"
	| "SidebarMenuItem"
	| "SidebarProvider"
	| "Toaster"
	| "Toast"
	| "ToastAction"
	| "ToastClose"
	| "ToastContent"
	| "ToastDescription"
	| "ToastProvider"
	| "ToastTitle"
	| "ToastViewport";

export type ShadcnPrimitiveSet = Partial<Record<AdditionalShadcnPrimitiveName, ElementType>> & {
	Accordion: ElementType;
	AccordionContent: ElementType;
	AccordionItem: ElementType;
	AccordionTrigger: ElementType;
	Alert: ElementType;
	AlertDescription: ElementType;
	AlertTitle: ElementType;
	Avatar: ElementType;
	AvatarFallback: ElementType;
	AvatarImage: ElementType;
	Badge: ElementType;
	Button: ElementType;
	ButtonGroup: ElementType;
	Card: ElementType;
	CardContent: ElementType;
	CardDescription: ElementType;
	CardHeader: ElementType;
	CardTitle: ElementType;
	Carousel: ElementType;
	CarouselContent: ElementType;
	CarouselItem: ElementType;
	CarouselNext: ElementType;
	CarouselPrevious: ElementType;
	Checkbox: ElementType;
	Collapsible: ElementType;
	CollapsibleContent: ElementType;
	CollapsibleTrigger: ElementType;
	Dialog: ElementType;
	DialogContent?: ElementType;
	DialogDescription: ElementType;
	DialogHeader: ElementType;
	DialogTitle: ElementType;
	Drawer: ElementType;
	DrawerContent: ElementType;
	DrawerDescription: ElementType;
	DrawerHeader: ElementType;
	DrawerTitle: ElementType;
	DropdownMenu: ElementType;
	DropdownMenuContent?: ElementType;
	DropdownMenuItem: ElementType;
	DropdownMenuTrigger: ElementType;
	Input: ElementType;
	Label: ElementType;
	Pagination: ElementType;
	PaginationContent: ElementType;
	PaginationEllipsis: ElementType;
	PaginationItem: ElementType;
	PaginationLink: ElementType;
	PaginationNext: ElementType;
	PaginationPrevious: ElementType;
	Popover: ElementType;
	PopoverContent?: ElementType;
	PopoverTrigger: ElementType;
	Progress: ElementType;
	RadioGroup: ElementType;
	RadioGroupItem: ElementType;
	Select: ElementType;
	SelectContent: ElementType;
	SelectItem: ElementType;
	SelectTrigger: ElementType;
	SelectValue: ElementType;
	Separator: ElementType;
	Skeleton: ElementType;
	Slider: ElementType;
	Switch: ElementType;
	Tabs: ElementType;
	TabsContent: ElementType;
	TabsList: ElementType;
	TabsTrigger: ElementType;
	Table: ElementType;
	TableBody: ElementType;
	TableCaption: ElementType;
	TableCell: ElementType;
	TableHead: ElementType;
	TableHeader: ElementType;
	TableRow: ElementType;
	Textarea: ElementType;
	Toggle: ElementType;
	ToggleGroup: ElementType;
	ToggleGroupItem: ElementType;
	Tooltip: ElementType;
	TooltipContent?: ElementType;
	TooltipProvider?: ElementType;
	TooltipTrigger: ElementType;
};

export type ShadcnPrimitiveBase = "base-ui" | "react-aria" | "radix";

export type CreateShadcnComponentsOptions = {
	base: ShadcnPrimitiveBase;
};
