/* Generated by @json-render-extended/playground. Do not edit manually. */

import { z } from "zod";

export const componentDefinitions = {
	PackageSurface: {
		props: z.object({
			title: z.string().optional(),
		}),
		description: "Project-local component materialized from docs/package-surface.",
		example: {},
	},
};
