/* Generated by @json-render-extended/playground. Do not edit manually. */
"use client";

import type { BaseComponentProps } from "@json-render/react";
import { createBaseUiComponents as createRuntimeComponents0 } from "@json-render-extended/shadcn/base-ui";
import * as localPrimitives0 from "@/components/ui/alert";
import * as localPrimitives1 from "@/components/ui/badge";
import * as localPrimitives2 from "@/components/ui/card";
import { PackageSurface } from "../../components/generated/package-surface";

const runtimeComponents0 = createRuntimeComponents0(
	localPrimitives0,
	localPrimitives1,
	localPrimitives2,
);

function PackageSurfaceRenderer({ props }: BaseComponentProps<Record<string, unknown>>) {
	return <PackageSurface {...props} />;
}

export const components = {
	Alert: runtimeComponents0.Alert,
	Badge: runtimeComponents0.Badge,
	Card: runtimeComponents0.Card,
	PackageSurface: PackageSurfaceRenderer,
};
